/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PepperlFuchsRouteImport } from './routes/pepperl-fuchs'
import { Route as ObrienAmatekRouteImport } from './routes/obrien-amatek'
import { Route as KontaktaiRouteImport } from './routes/kontaktai'
import { Route as IndexRouteImport } from './routes/index'

const PepperlFuchsRoute = PepperlFuchsRouteImport.update({
  id: '/pepperl-fuchs',
  path: '/pepperl-fuchs',
  getParentRoute: () => rootRouteImport,
} as any)
const ObrienAmatekRoute = ObrienAmatekRouteImport.update({
  id: '/obrien-amatek',
  path: '/obrien-amatek',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktaiRoute = KontaktaiRouteImport.update({
  id: '/kontaktai',
  path: '/kontaktai',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/kontaktai': typeof KontaktaiRoute
  '/obrien-amatek': typeof ObrienAmatekRoute
  '/pepperl-fuchs': typeof PepperlFuchsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/kontaktai': typeof KontaktaiRoute
  '/obrien-amatek': typeof ObrienAmatekRoute
  '/pepperl-fuchs': typeof PepperlFuchsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/kontaktai': typeof KontaktaiRoute
  '/obrien-amatek': typeof ObrienAmatekRoute
  '/pepperl-fuchs': typeof PepperlFuchsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/kontaktai' | '/obrien-amatek' | '/pepperl-fuchs'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/kontaktai' | '/obrien-amatek' | '/pepperl-fuchs'
  id: '__root__' | '/' | '/kontaktai' | '/obrien-amatek' | '/pepperl-fuchs'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  KontaktaiRoute: typeof KontaktaiRoute
  ObrienAmatekRoute: typeof ObrienAmatekRoute
  PepperlFuchsRoute: typeof PepperlFuchsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pepperl-fuchs': {
      id: '/pepperl-fuchs'
      path: '/pepperl-fuchs'
      fullPath: '/pepperl-fuchs'
      preLoaderRoute: typeof PepperlFuchsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/obrien-amatek': {
      id: '/obrien-amatek'
      path: '/obrien-amatek'
      fullPath: '/obrien-amatek'
      preLoaderRoute: typeof ObrienAmatekRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontaktai': {
      id: '/kontaktai'
      path: '/kontaktai'
      fullPath: '/kontaktai'
      preLoaderRoute: typeof KontaktaiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  KontaktaiRoute: KontaktaiRoute,
  ObrienAmatekRoute: ObrienAmatekRoute,
  PepperlFuchsRoute: PepperlFuchsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
